# GitHub Action for building Libuv
name: macOS

on:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-10.15
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - {lib_uv: 1.44.1}
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Setup
        run: |
          brew install ninja
      - name: Configure
        run: |
          curl -L https://github.com/libuv/libuv/archive/v${{ matrix.config.lib_uv }}.tar.gz | tar xzf -
          cd libuv-${{ matrix.config.lib_uv }}
          mkdir build
          cd build
          cmake .. -DBUILD_TESTING=ON -G Ninja
      - name: Build
        run: |
          cd libuv-${{ matrix.config.lib_uv }}
          cmake --build build
          ls -lh build
      - name: Upload/Commit to Repo
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          mkdir -p lib/macOS/
          cp -f libuv-${{ matrix.config.lib_uv }}/build/libuv.1.0.0.dylib lib/macOS/
          git add lib
          git commit -m "created libuv.1.0.0.dylib - for macOS 10.15"
          git push -q
