# GitHub Action for building Libuv
name: macOS

on:
  release:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Setup
        run: |
          brew install ninja
      - name: Configure
        run: |
          curl -L https://github.com/libuv/libuv/archive/v1.44.1.tar.gz | tar xzf -
          cd libuv-1.44.1
          mkdir build
          cd build
          cmake .. -DBUILD_TESTING=ON -G Ninja
      - name: Build
        run: |
          cd libuv-1.44.1
          cmake --build build
          ls -lh build
