# GitHub Action for building Libuv
name: Windows

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-${{ matrix.config.server }}
    name: build-${{ matrix.config.toolchain}}-${{ matrix.config.arch}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {toolchain: Visual Studio 16 2019, arch: x64, server: 2019, lib_uv: 1.44.1}
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Build
        shell: cmd
        run: |
          curl -L https://github.com/libuv/libuv/archive/refs/tags/v${{ matrix.config.lib_uv }}.zip --output libuv.zip
          unzip -xoq libuv.zip
          cd libuv-${{ matrix.config.lib_uv }}
          mkdir -p build
          cd build
          cmake .. -DBUILD_TESTING=ON -G "${{ matrix.config.toolchain }}" -A ${{ matrix.config.arch }}
          cmake --build .
      - name: platform_output
        shell: cmd
        run: |
          libuv-${{ matrix.config.lib_uv }}\\build\\Debug\\uv_run_tests.exe platform_output
      - name: platform_output_a
        shell: cmd
        run: |
          libuv-${{ matrix.config.lib_uv }}\\build\\Debug\\uv_run_tests_a.exe platform_output
      - name: Test
        shell: cmd
        run: |
          dir .
          cd libuv-${{ matrix.config.lib_uv }}
          dir .
          cd build
          dir .
          ctest -C Debug -V
