# GitHub Action for building Libuv
name: Windows

on:
  release:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-${{ matrix.config.server }}
    name: windows-${{ matrix.config.toolchain}}-${{ matrix.config.arch}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {toolchain: Visual Studio 16 2019, arch: x64, server: 2019, lib_uv: 1.44.1}
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Build
        shell: cmd
        run: |
          curl -L https://github.com/libuv/libuv/archive/refs/tags/v${{ matrix.config.lib_uv }}.zip --output libuv.zip
          unzip -xoq libuv.zip
          cd libuv-${{ matrix.config.lib_uv }}
          mkdir -p build
          cd build
          cmake .. -DBUILD_TESTING=ON -G "${{ matrix.config.toolchain }}" -A ${{ matrix.config.arch }}
          cmake --build .
          dir Debug
      - name: Upload/Commit to Repo
        shell: cmd
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          mkdir lib\Windows\
          copy /Y libuv-${{ matrix.config.lib_uv }}\build\Debug\uv.dll lib\Windows\ /B
          git add lib
          git commit -m "GitHub Actions created uv.dll - Windows x64"
          git push
          copy /Y libuv-${{ matrix.config.lib_uv }}\include\*.* include\
          copy /Y libuv-${{ matrix.config.lib_uv }}\include\uv\*.* include\uv\
          git add include
          git commit -m "Libuv *.h headers"
          git push
