# GitHub Action for building Libuv
name: Windows

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'What version of libuv to compile and commit to repo?'
        required: true
        default: 1.44.1
        type: number

jobs:
  windows:
    runs-on: windows-${{ matrix.config.server }}
    continue-on-error: true
    name: windows-${{ matrix.config.toolchain}}-${{ matrix.config.arch}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {toolchain: Visual Studio 16 2019, arch: x64, server: 2019, lib_uv: $version}
      env:
        version: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Build
        shell: cmd
        run: |
          curl -L https://github.com/libuv/libuv/archive/refs/tags/v${{ matrix.config.lib_uv }}.zip --output libuv.zip
          unzip -xoq libuv.zip
          cd libuv-${{ matrix.config.lib_uv }}
          mkdir -p build
          cd build
          cmake .. -DBUILD_TESTING=ON -DBUILDING_UV_SHARED=1 -G "${{ matrix.config.toolchain }}" -A ${{ matrix.config.arch }}
          cmake --build .
          dir Debug
      - name: Upload/Commit to Repo
        shell: cmd
        run: |
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          mkdir lib\Windows\
          copy /Y libuv-${{ matrix.config.lib_uv }}\build\Debug\uv.dll lib\Windows\
          git add lib
          git commit -m "created uv.dll - for Windows x64"
          git push -q
          copy /Y libuv-${{ matrix.config.lib_uv }}\include\*.* headers\original
          copy /Y libuv-${{ matrix.config.lib_uv }}\include\uv\*.* headers\original\uv\
          git add headers
          git commit -m "Libuv *.h headers"
          git push -q
